name: build

on:
  # push:
  #   branches: [ lab1-dev-1 ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  build-unix:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]

    steps:
      - name: Build
        run: ./mvnw clean package
        shell: bash

  build-windows:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]

    steps:
      - name: Build
        run: mvnw.cmd clean package
        shell: cmd
